### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by hroncok**

### CODE REVIEW

**Comment by hroncok** [comment]
Please remove .DS_Store and add it to .gitignore.

I'd also suggest to remove some of the Mladeč ABS profiles, as we don't use them anymore (or at least merge them to one)
￼
Some of the printers are supposed to be obsoleted by hotends. I.e. all Rebelixes and Prusa i3s

**Comment by syky27** [comment]
All of the i3's we are using has same hotend - J-Head

**Comment by hroncok** [comment]
Yes, that's why Prusa i3 profile is obsoleted by J-Head (and should be gone)

**Comment by hroncok** [comment]
Why did you deleted ABS 3 Floria?

**Comment by syky27** [comment]
Because it was secretly 1.75 which already exists...

**Comment by hroncok** [comment]
Then I guess we need one for that. Is the ABS 3 Floria Brown somehow special, or it could be renamed to ABS 3 Floria?

**Comment by syky27** [comment]
Well, It, not generic ABS 3 Floria, this one is strictly made to meet requirements  of Floria Brown, there shall be generic one as well, but I dont have access to the filament right now, so there is no way to create new filament config, I can make one when I get my hands on one...

**Comment by hroncok** [comment]
- [H] J-Head.ini - OK
- [H] PrusaNozzle.ini - OK
- [H] 3Draty.ini - OK
- [P] CZ.NIC.ini - obsoleted by [H] PrusaNozzle.ini - should be deleted
- [P] i3 Blue.ini - obsoleted by [H] J-Head.ini - should be deleted 
- [P] Lulzbot.ini - OK
- [P] PrusaMendel Arcig.ini - OK
- [P] PrusaMendel Green.ini - OK
- [P] PrusaMendel Yellow.ini - OK
- [P] Rebelix SUMA J-Head.ini - Don't know, seems different than [H] J-Head.ini?
- [P] Rebelix yellow 3Draty.ini - Does that even exist?

**Comment by syky27** [comment]
[P] Rebelix SUMA J-Head.ini - Don't know, seems different than [H] J-Head.ini - it is it has different retract...
[P] Rebelix yellow 3Draty.ini - Does that even exist?  - I have no clue, I hope so...

**Comment by hroncok** [comment]
[P] Rebelix yellow 3Draty.ini - It has always had JHead, and it does not differ:

```
$ diff \[P\]\ Rebelix\ yellow\ 3Draty.ini \[H\]\ J-Head.ini 
1c1
< # generated by Slic3r 1.1.7 on Mon Aug 11 13:34:18 2014
---
> # generated by Slic3r 1.1.7 on Thu Feb 19 16:07:32 2015
```

Delete that as well.

Also, please squash all the commits (the ones in this branch, not in master) together, so we get rid of the middle steps in the history.

**Comment by hroncok** [comment]
Squash it to 1 commit and I'm fine with it ;)

**Comment by hroncok** [comment]
Squash everything in this PR to 1 commit, please

**Pull request merged**
